title: A Journey through Pottery
logo: /images/Picture1.jpg
description: This is a place of selfdiscovery through writing about pottery. [Contact me](<scaroagustina@gmail.com>)
show_downloads: false
theme: jekyll-theme-minimal
